### ISSUE TITLE
Keep releases on playlists for a set amount of time only

### ISSUE THREAD

**Issue by Aaantoni** [Selbi182/SpotifyDiscoveryBot#4]
From my understanding, the playlist rotation occurs only once the song limit is reached, resulting in playlists having possibly hundreds of (eventually) outdated releases.

Is there a chance to implement a feature that would remove releases from playlists after e.g. a month or two, so that they only would have truly the newest and freshest releases?

**Comment by Selbi182** [comment]
I suppose it could be done, but what exactly is the intention? The bot adds the new releases at the top of the playlists, so the old stuff should naturally get pushed out of sight over time. Furthermore, the playlists are owned by your user account, so shouldn't Ctrl+A and Del do the trick as well?

**Comment by Selbi182** [comment]
Ah, I see. Well, how exactly do you envision this to be implemented? Some sort of "cut-off days" parameter to be passed on launch that automatically purges songs that have been added more than those many days ago?

**Comment by Selbi182** [comment]
Sounds doable. I'll have to experiment a little with this, but this shouldn't be so difficult. I'll get back to you later today.

**Comment by Selbi182** [comment]
Haha, that's quite alright. I like working on new features :)

**Comment by Selbi182** [comment]
Okay, this was quite a bit easier than I expected, since I already had most of the logic built in for other functionality. A new release including what I now call AutoPurging is live: https://github.com/Selbi182/SpotifyDiscoveryBot/releases/tag/v1.4

To enable it, add the following line to `application.properties`:
```
spotify.discovery.crawl.auto_purge_days = 7
```
Replace 7 with however many days you want it to wait before it counts as expired.

Please let me know if this works as expected! :)

**Comment by Selbi182** [comment]
Just curious: What expiration date did you choose?

**Comment by Selbi182** [comment]
Alright. Would love to hear your feedback in about a month then to see if it works as intended :)

**Comment by Selbi182** [comment]
Oh, that's absolutely possible. Just wish you had told me that from the start cause now I built the whole thing with a single purge in mind and would need to rewrite everything 😅

I'll see what I can do.

**Comment by Selbi182** [comment]
That's alright, don't worry!

**Comment by Selbi182** [comment]
https://github.com/Selbi182/SpotifyDiscoveryBot/releases/tag/v1.5

New release with individual expiration days customization per playlist is live!
